import type { Metadata } from "next";
import Authprovider from "./context/authProvider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Navbar from "@/components/Navbar";

// 🩹 Temporary patch: fallback font variables using static class names
const geistSans = { variable: "--font-geist-sans" };
const geistMono = { variable: "--font-geist-mono" };

export const metadata: Metadata = {
  title: "Mystery Message",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased font-sans">
        <Authprovider>
          <Navbar />
          {children}
          <Toaster position="bottom-right"
        richColors
        toastOptions={{
          duration: 4000,
          style: {
            background: "#111111", // dark AMOLED style
            color: "#ffffff",      // white text
            border: "1px solid #444", // subtle border
            borderRadius: "12px",     // rounded corners
            boxShadow: "0 4px 12px rgba(255,255,255,0.05)", // subtle glow
            fontFamily: "Inter, Geist Sans, system-ui",
          },
        }} />
        </Authprovider>
      </body>
    </html>
  );
}
